client dockernet {
	ipaddr = 127.0.0.1/32
	secret = testing123
}

client ubuntu-radius {
	ipaddr = 192.168.122.110/32
	secret = testing123
}

client docker-gateway {
	ipaddr = 172.20.0.1/32
	secret = testing123
}